import type {
  ExperienceAssistiveInference,
  ExperienceAssistiveInferenceCautionCode,
  ExperienceAssistiveInferenceCode,
  ExperienceAssistiveInferenceConfidence,
  ExperienceChecklistContribution,
  ExperienceChecklistItem,
  ExperienceChecklistItemStatus,
  ExperienceEpisode,
  ExperienceEpisodeArtifact,
  ExperienceEpisodeArtifactKind,
  ExperienceEpisodeBoundaryReason,
  ExperienceEpisodeOutcome,
  ExperienceEpisodeRole,
  ExperienceEvidenceChain,
  ExperienceEvidenceKind,
  ExperienceEvidenceRef,
  ExperienceFeedbackAttribution,
  ExperienceFeedbackAttributionReason,
  ExperienceFeedbackAttributionRole,
  ExperienceFeedbackSignal,
  ExperienceFeedbackSignalType,
  ExperienceGoalEvidenceRef,
  ExperienceGoalSlice,
  ExperienceGoalSliceReasonCode,
  ExperienceInvocation,
  ExperienceMessageRange,
  ExperienceOrchestrationEdge,
  ExperienceOrchestrationEdgeKind,
  ExperienceOrchestrationEdgeStatus,
  ExperienceOutcomeClosure,
  ExperienceParentReason,
  ExperienceReviewBasisCode,
  ExperienceReviewIndicators,
  ExperienceReviewPriority,
  ExperienceReviewerReport,
  ExperienceReviewerReportFinding,
  ExperienceReviewerReportFindingLevel,
  ExperienceReviewerReportFindingSource,
  ExperienceReviewerReportScope,
  ExperienceReviewerReportStep,
  ExperienceReviewerReportStepStatus,
  ExperienceRuleFinding,
  ExperienceRuleFindingCode,
  ExperienceRuleFindingLevel,
  ExperienceRuntimeSkillType,
  ExperienceRuntimeSkillTypeSource,
  ExperienceSessionStory,
  ExperienceSessionStoryAnswer,
  ExperienceSessionStoryAnswerKey,
  ExperienceSessionStoryGoalSlice,
  ExperienceSessionStoryGraphEdge,
  ExperienceSessionStoryGraphNode,
  ExperienceSessionStoryNode,
  ExperienceSessionStoryNodeKind,
  ExperienceSessionStorySkillLink,
  ExperienceSessionStorySkillRole,
  ExperienceSessionStorySubagentDispatch,
  ExperienceSessionSummary,
  ExperienceSkillSegment,
  ExperienceSkillSummary,
  ExperienceStoryContext,
  ExperienceTimelineBranch,
  ExperienceTimelineEvent,
  ExperienceTraceTimeline,
  ExperienceTimelineTree,
  ObservationExperienceReport,
} from './contracts/experience.js';

import {
  ObservationReviewState,
} from './contracts/review.js';

import {
  OBSERVATION_EXPERIENCE_SCHEMA_VERSION,
} from './experience/report-structure.js';

export {
  findNegativeFeedbackMatches,
  findPositiveFeedbackMatches,
  findUserCorrectionMatches,
  findUserGoalShiftMatches,
  hasNegativeFeedbackSignal,
  hasPositiveFeedbackSignal,
  hasUserCorrectionSignal,
  hasUserGoalShiftSignal,
} from './inbox/feedback-matchers.js';
export type { TextMatchRange } from './inbox/feedback-matchers.js';
export { projectTraceSessionTimeline } from './experience/timeline.js';
export { OBSERVATION_EXPERIENCE_SCHEMA_VERSION };
export {
  compactObservationExperienceReport,
  normalizeObservationExperienceReport,
} from './experience/report-codec.js';
export {
  aggregateExperienceChecklistItemStatus,
  foldExperienceChecklistItems,
  hasRecognizableUserGoalText,
  isExperienceTraceInProgress,
} from './experience/review-checklist.js';
export type {
  PersistedExperienceInvocation,
  PersistedExperienceReviewerReport,
  PersistedExperienceSession,
  PersistedExperienceSessionStory,
  PersistedObservationExperienceReport,
} from './experience/report-codec.js';

export type {
  ExperienceAssistiveInference,
  ExperienceAssistiveInferenceCautionCode,
  ExperienceAssistiveInferenceCode,
  ExperienceAssistiveInferenceConfidence,
  ExperienceChecklistContribution,
  ExperienceChecklistItem,
  ExperienceChecklistItemStatus,
  ExperienceEpisode,
  ExperienceEpisodeArtifact,
  ExperienceEpisodeArtifactKind,
  ExperienceEpisodeBoundaryReason,
  ExperienceEpisodeOutcome,
  ExperienceEpisodeRole,
  ExperienceEvidenceChain,
  ExperienceEvidenceKind,
  ExperienceEvidenceRef,
  ExperienceFeedbackAttribution,
  ExperienceFeedbackAttributionReason,
  ExperienceFeedbackAttributionRole,
  ExperienceFeedbackSignal,
  ExperienceFeedbackSignalType,
  ExperienceGoalEvidenceRef,
  ExperienceGoalSlice,
  ExperienceGoalSliceReasonCode,
  ExperienceInvocation,
  ExperienceMessageRange,
  ExperienceOrchestrationEdge,
  ExperienceOrchestrationEdgeKind,
  ExperienceOrchestrationEdgeStatus,
  ExperienceOutcomeClosure,
  ExperienceParentReason,
  ExperienceReviewBasisCode,
  ExperienceReviewIndicators,
  ExperienceReviewPriority,
  ExperienceReviewerReport,
  ExperienceReviewerReportFinding,
  ExperienceReviewerReportFindingLevel,
  ExperienceReviewerReportFindingSource,
  ExperienceReviewerReportScope,
  ExperienceReviewerReportStep,
  ExperienceReviewerReportStepStatus,
  ExperienceRuleFinding,
  ExperienceRuleFindingCode,
  ExperienceRuleFindingLevel,
  ExperienceRuntimeSkillType,
  ExperienceRuntimeSkillTypeSource,
  ExperienceSessionStory,
  ExperienceSessionStoryAnswer,
  ExperienceSessionStoryAnswerKey,
  ExperienceSessionStoryGoalSlice,
  ExperienceSessionStoryGraphEdge,
  ExperienceSessionStoryGraphNode,
  ExperienceSessionStoryNode,
  ExperienceSessionStoryNodeKind,
  ExperienceSessionStorySkillLink,
  ExperienceSessionStorySkillRole,
  ExperienceSessionStorySubagentDispatch,
  ExperienceSessionSummary,
  ExperienceSkillSegment,
  ExperienceSkillSummary,
  ExperienceStoryContext,
  ExperienceTimelineBranch,
  ExperienceTimelineEvent,
  ExperienceTraceTimeline,
  ExperienceTimelineTree,
  ObservationExperienceReport,
  ObservationReviewState,
};

export {
  assistiveInferenceForEvidence,
  buildObservationExperienceReport,
  ruleFindingsForEvidence,
  timelineIndicators,
} from './experience/report-assembly.js';
