export { createEvaluationEngine } from './evaluation-core/engine/index.js';
export type {
  EvaluationEngine,
  EvaluationEngineClock,
  EvaluationEngineAnalysisBinding,
  EvaluationEngineEvaluatorBinding,
  EvaluationEngineExecutorBinding,
  EvaluationEngineEventWriter,
  EvaluationEngineRuntime,
  EvaluationEngineRuntimeBindings,
  EvaluationExtensionValidationRequest,
  EvaluationRun,
  EvaluationRunArtifacts,
  EvaluationRunOptions,
  EvaluationRunResult,
  Evaluator,
  Executor,
  PreparedEvaluation,
  PreparedEvaluationRunOptions,
  PartialEvaluationRunArtifacts,
} from './evaluation-core/engine/index.js';

export {
  ANALYSIS_BUNDLE_SCHEMA_VERSION,
  BUDGET_SUMMARY_SCHEMA_VERSION,
  EVALUATION_BUNDLE_SCHEMA_VERSION,
  EVALUATION_DEFINITION_SCHEMA_VERSION,
  EVALUATION_EVENT_SCHEMA_VERSION,
  EVALUATION_REPORT_SCHEMA_VERSION,
  EXECUTION_FACTS_SCHEMA_VERSION,
  EXECUTOR_CAPABILITIES_SCHEMA_VERSION,
  EVALUATION_SERIES_DEFINITION_SCHEMA_VERSION,
  EVALUATION_SERIES_PLAN_SCHEMA_VERSION,
  EVALUATION_SERIES_REPORT_SCHEMA_VERSION,
  SERIES_ANALYSIS_BUNDLE_SCHEMA_VERSION,
  EXECUTION_BUNDLE_SCHEMA_VERSION,
  MEASUREMENT_POLICY_SCHEMA_VERSION,
  canonicalizeJson,
  digestCanonicalJson,
  schemaIdentityKey,
  prepareEvaluationSeriesPlan,
  createEvaluationSeriesDefinition,
  createEvaluationSeriesMemberSource,
  parseEvaluationSeriesPlan,
  parseSeriesAnalysisBundleDocument,
  parseEvaluationSeriesReportDocument,
} from './evaluation-core/contracts/index.js';
export type {
  AnalysisBundle,
  BudgetLedgerEntry,
  BudgetScopeSummary,
  BudgetSummary,
  BudgetTermination,
  BudgetUsageTotals,
  AnalysisCohortDefinition,
  AnalysisCoverage,
  AnalysisRecord,
  AnalysisSampleInput,
  CapturedContent,
  ComparisonDefinition,
  ContentDescriptor,
  CoreSchemaValidationContext,
  CoreSchemaValidator,
  DecisionPolicyDefinition,
  DecisionResult,
  EvaluationBundle,
  EvaluationCoverage,
  EvaluationDataset,
  EvaluationDefinition,
  EvaluationError,
  EvaluationEvent,
  EvaluationReport,
  EvaluationSample,
  EvaluationStatus,
  EvaluationSeriesMembership,
  EvaluatorDefinition,
  EvaluatorMeasurementIdentity,
  ExecutionBundle,
  ExecutionCoverage,
  ExecutionFacts,
  ExecutionRecord,
  ExperimentDesign,
  JsonValue,
  MeasurementPolicy,
  MetricDefinition,
  MetricObservation,
  Provenance,
  RuntimeIdentity,
  SchemaIdentity,
  Sha256Digest,
  TargetDefinition,
  TargetExecutionRequirements,
  UsageRecord,
  EvaluationSeriesDefinition,
  EvaluationSeriesDefinitionInput,
  EvaluationSeriesPlan,
  EvaluationSeriesReport,
  EvaluationSeriesMemberSource,
  SeriesAnalysisBundle,
  SeriesAnalysisRecord,
  SeriesComparabilityAssessment,
  SeriesDecisionResult,
  SeriesMemberCoverage,
  SeriesMemberReference,
} from './evaluation-core/contracts/index.js';

export { runEvaluationSeries } from './evaluation-core/series/index.js';
export type {
  EvaluationSeriesRunOptions,
  EvaluationSeriesRunResult,
  EvaluationSeriesRuntimePorts,
  SeriesAnalysisNodeContext,
  SeriesAnalysisNodeInput,
  SeriesAnalysisNodeOutput,
  SeriesAnalysisNodeRuntime,
  SeriesDecisionContext,
  SeriesDecisionOutput,
  SeriesDecisionRuntime,
} from './evaluation-core/series/index.js';

export type {
  AnalysisRuntimeRequirement,
  DecisionPolicyCapabilities,
  EvaluatorCapabilities,
  EvaluatorRuntimeRequirement,
  ExecutorCapabilities,
  ExecutorRuntimeRequirement,
  ExtensionResolution,
  PreparationRuntime,
  ProtocolManifest,
  RuntimeResolution,
  SealedRunPlan,
} from './evaluation-core/compiler/index.js';

export type {
  ExecutionCache,
  ExecutionCacheEntry,
  ExecutionContent,
  ExecutionContentStore,
  ExecutionContentStoreRequest,
  ExecutionEventWriter,
  ExecutorAttemptContext,
  ExecutorAttemptResult,
  ExecutorRunContext,
  ExecutorTrialContext,
} from './evaluation-core/execution/index.js';

export type {
  EvaluationCache,
  EvaluationCacheEntry,
  EvaluationContent,
  EvaluationContentResolver,
  EvaluationContentStore,
  EvaluationContentStoreRequest,
  EvaluationEventWriter,
  EvaluatorAttemptContext,
  EvaluatorAttemptResult,
  EvaluatorBindingValue,
  EvaluatorObservation,
  EvaluatorRecordContext,
  EvaluatorRunContext,
} from './evaluation-core/evaluation/index.js';

export {
  BUILTIN_EXCLUDE_MISSING_POLICY,
  BUILTIN_HYPOTHESIS_INPUT_SCHEMA,
  BUILTIN_HYPOTHESIS_TABLE_SCHEMA,
  BUILTIN_INTERVAL_RESULT_SCHEMA,
  BUILTIN_PROGRESS_DECISION_POLICY,
  BUILTIN_SCALAR_RESULT_SCHEMA,
  createBuiltinAnalysisNodes,
  createBuiltinAnalysisSchemaValidators,
  createBuiltinDecisionPolicies,
  createBuiltinMissingPolicies,
  resolveBuiltinAnalysisRuntime,
} from './evaluation-core/analysis/index.js';

export {
  CORE_EVOLUTION_EVIDENCE_SCHEMA_VERSION,
  CORE_GOLD_COMPARISON_SCHEMA_VERSION,
  CoreDownstreamProjectionError,
  compareGoldToCoreRun,
  projectCoreArtifactGraph,
  projectCoreEvolutionEvidence,
} from './eval-workflows/downstream-projections/index.js';

export {
  CORE_STUDIO_RUN_CARD_SCHEMA_VERSION,
  CORE_STUDIO_RUN_DETAIL_SCHEMA_VERSION,
  createCoreStudioCatalog,
  projectCoreStudioRunCard,
  projectCoreStudioRunDetail,
} from './eval-workflows/studio-catalog/index.js';
export type {
  CoreStudioAnalysisRecord,
  CoreStudioBudget,
  CoreStudioCatalog,
  CoreStudioDecision,
  CoreStudioEvaluationRecord,
  CoreStudioExecutionRecord,
  CoreStudioMetricObservation,
  CoreStudioProvenance,
  CoreStudioRunCard,
  CoreStudioRunDetail,
  CoreStudioRuntimeIdentity,
  CoreStudioUsage,
} from './eval-workflows/studio-catalog/index.js';
export type {
  CompareGoldToCoreRunInput,
  CoreGoldDatasetInput,
  CoreDownstreamProjectionErrorCode,
  CoreEvolutionAnalysisEvidence,
  CoreEvolutionDecisionEvidence,
  CoreEvolutionEvidence,
  CoreEvolutionMemberEvidence,
  CoreGoldComparisonResult,
  CoreGoldAgreementResult,
  CoreGoldComparisonRow,
  CoreGoldMetricSelector,
  ProjectCoreArtifactGraphInput,
  ProjectCoreEvolutionEvidenceInput,
} from './eval-workflows/downstream-projections/index.js';
export type {
  AnalysisDecisionPolicy,
  AnalysisMetricRow,
  AnalysisMissingPolicy,
  AnalysisNodeExecutionContext,
  AnalysisNodeExecutionResult,
  AnalysisNodeImplementation,
  AnalysisNodeInput,
  AnalysisNodeRun,
  AnalysisNodeRunContext,
  DecisionPolicyContext,
  DecisionPolicyOutput,
  MissingPolicyContext,
} from './evaluation-core/analysis/index.js';
